password_users/basic_passwords/urls.py
from django.urls import path
from basic_passwords import views

#TEMPLATE URLS
app_name='basic_passwords'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
]

password_users/password_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_passwords import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_passwords/',include('basic_passwords.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

password_users/basic_passwords/models.py
from django.db import models


from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    
    
    #additional contents

    portfolio_site=models.URLField(blank=True)
    
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

password_users/basic_passwords/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_passwords.models import UserProfileInfo


class UserForm(forms.ModelForm):
    
    password=forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model=User
        fields=('username','email','password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

password_users/basic_passwords/views.py
from django.shortcuts import render
from basic_passwords.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    return render(request,'basic_passwords/index.html')

@login_required
def special(request):
    return HttpResponse("You are Logged in! Congrats")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    
    registered=False
    
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile=profile_form.save(commit=False)
            profile.user=user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
                     
            profile.save()
            
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
            
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
        
    return render(request,'basic_passwords/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,'registered':registered})



def user_login(request):
    
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        user=authenticate(username=username,password=password)
        
        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("Account not Active")
        else:
            print("Login Failed")
            print("Username:{} and password:{}".format(username,password))
            
            return HttpResponse("Invalid Login Deatils")

    else:
        return render(request,'basic_passwords/login.html',{})        
        

password_users/templates/basic_passwords/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%url 'index'%}">DJANGO</a></li>
                <li><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-link" href="{%url 'basic_passwords:register'%}">Register</a></li>
           
           
                {%if user.is_authenticated%}
                 <li><a class='navbar-link' href="{%url 'logout'%}">Logout</a></li>
                {% else %}
                 <li><a class='navbar-link' href="{%url 'basic_passwords:user_login'%}">Login</a></li>
                
                {% endif %}
            </ul>
        </div>
    </nav>
    {%block body_block%}
    {%endblock%}

</body>
</html>

password_users/templates/basic_passwords/index.html
{%extends "basic_passwords/base.html"%}
{%block body_block%}

<div class="jumbotron">
    <h1>django level five</h1>
</div>

{%endblock%}

password_users/templates/basic_passwords/login.html
{%extends 'basic_passwords/base.html'%}
{%block body_block%}

<div class="jumbotron">
    <h1>Please Login</h1>

    <form action="{%url 'basic_passwords:user_login'%}" method="POST">
        {% csrf_token %}
        <label for="username">UserName:</label>
        <input type="text" name="username" placeholder="Enter UserName">

        <label for="password">Password:</label>
        <input type="password" name="password" id="">

        <input type="submit" value="Login">
    </form>
</div>

{%endblock%}

password_users/templates/basic_passwords/registration.html
{%extends "basic_passwords/base.html"%}
{%load static%}

{%block body_block%}

<div class="jumbotron">
    {%if registered%}
        <h1>Thanks for Registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <h2>Fill The Form</h2>

        <form enctype="multipart/form-data" method="post" >
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" value="Register">

        </form>


    {% endif %}
</div>

{%endblock%}